name: Run linters
description: Running linters
#inputs:
#  PY_FILES:
#    description: '.py files for checking'
#    required: true
#  COMMAND:
#    description: 'Command for starting linters (Example: mypy, ruff check, etc.)'
#    required: true

runs:
  using: composite
  steps:
    - name: Prepare Environment
      uses: ./.github/actions/prepare

    - name: Linting
      shell: bash
      run: {{ inputs.COMMAND }} ${{ inputs.PY_FILES }}
