name: Linters Call

on: workflow_call

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: PY_FILES
        run: echo ${PY_FILES}

      - name: Prepare Environment
        uses: ./.github/actions/prepare

      - name: Linting
        run: ruff .

  deptry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: PY_FILES
        run: echo ${PY_FILES}

      - name: Prepare Environment
        uses: ./.github/actions/prepare

      - name: Linting
        run: deptry .

  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: PY_FILES
        run: echo ${PY_FILES}

      - name: Prepare Environment
        uses: ./.github/actions/prepare

      - name: Type checking
        run: mypy .
