name: Code Linters Call

on:
  workflow_call:
    inputs:
      PY_FILES:
        description: 'Changed py files in PR'
        required: true
        type: string

# TODO: вынести в отдельную параметризированный action lint
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare Environment
        uses: ./.github/actions/prepare

      - name: Linting
        run: ruff check ${{ inputs.PY_FILES }}

  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare Environment
        uses: ./.github/actions/prepare

      - name: Type checking
        run: mypy ${{ inputs.PY_FILES }}
