name: Linters

on: workflow_call

env:
  PY_FILES_1: git diff origin/${{ github.base_ref }} origin/${{ github.head_ref }} --name-only --diff-filter=d | grep "\.py"
#  PY_FILES_2: ${{ git diff origin/${{ github.base_ref }} origin/${{ github.head_ref }} --name-only --diff-filter=d | grep "\.py" }}
  PY_FILES_3: $(git diff origin/${{ github.base_ref }} origin/${{ github.head_ref }} --name-only --diff-filter=d | grep "\.py")
  PY_FILES_4: 'git diff origin/${{ github.base_ref }} origin/${{ github.head_ref }} --name-only --diff-filter=d | grep "\.py"'

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: PY_FILES_1
        run: echo ${PY_FILES_1}

#      - name: PY_FILES_2
#        run: echo ${PY_FILES_2}

      - name: PY_FILES_3
        run: echo ${PY_FILES_3}

      - name: PY_FILES_4
        run: echo ${PY_FILES_4}

      - uses: actions/checkout@v3

      - name: Prepare Environment
        uses: ./.github/actions/prepare

      - name: Linting
        run: ruff .

  deptry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Prepare Environment
        uses: ./.github/actions/prepare

      - name: Linting
        run: deptry .

  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Prepare Environment
        uses: ./.github/actions/prepare

      - name: Type checking
        run: mypy .
