name: Linters

on: workflow_call

jobs:
  check_py_files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect .py files
        run: |
          {
            echo 'PY_FILES<<EOL'
            git diff origin/${{ github.base_ref }} origin/${{ github.head_ref }} --name-only --diff-filter=d | grep "\.py"
            echo EOL
          } >> "$GITHUB_ENV"

  call_linters:
    needs: check_py_files
    uses: ./.github/workflows/_linters.yml
