name: Linters

on: workflow_call

env:
  PY_FILES: git diff origin/${{ github.base_ref }} origin/${{ github.head_ref }} --name-only --diff-filter=d | grep "\.py"

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: PY_FILES
        run: echo $PY_FILES

      - uses: actions/checkout@v3

      - name: Prepare Environment
        uses: ./.github/actions/prepare

      - name: Linting
        run: ruff .

  deptry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Prepare Environment
        uses: ./.github/actions/prepare

      - name: Linting
        run: deptry .

  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Prepare Environment
        uses: ./.github/actions/prepare

      - name: Type checking
        run: mypy .
