name: Linters

on: workflow_call

jobs:
  check_changes:
    name: Detecting changes
    runs-on: ubuntu-latest
    outputs:
      PY_FILES: ${{ steps.search_py_files.outputs.PY_FILES }}
      REQUIREMENTS_CHANGED: ${{ steps.search_requirements_changed.outputs.REQUIREMENTS_CHANGED }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: search_py_files
        name: Detecting changes in .py files
        run: echo "PY_FILES=$(git diff origin/${{ github.base_ref }} origin/${{ github.head_ref }} --name-only --diff-filter=d | grep "\.py" | tr "\n" " ")" >> "$GITHUB_OUTPUT"

      - id: search_requirements_changed
        name: Detecting changes in requirements.txt / pyproject.toml
        run: echo "REQUIREMENTS_CHANGED=[ -z $(git diff origin/${{ github.base_ref }} origin/${{ github.head_ref }} --name-only --diff-filter=d | grep "req.*\.txt|pyproject\.toml" | tr "\n" " ") ] && echo "true" || echo "false"" >> "$GITHUB_OUTPUT"

  code_linters:
    name: Running code linters
    if: ${{ needs.check_changes.outputs.PY_FILES }}
    needs: check_changes
    uses: ./.github/workflows/code_linters.yml
    with:
      PY_FILES: ${{ needs.check_changes.outputs.PY_FILES }}

  requirements_linters:
    name: Running requirements linters
    if: ${{ needs.check_changes.outputs.REQUIREMENTS_CHANGED }} == "true" || ${{ needs.check_changes.outputs.PY_FILES }}
    needs: check_changes
    uses: ./.github/workflows/requirements_linters.yml
