name: Linting and Tests

on:
  workflow_call:
#    inputs:
#      username:
#        description: 'A username passed from the caller workflow'
#        default: 'john-doe'
#        required: false
#        type: string

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Prepare Environment
        uses: ./.github/actions/prepare

      - name: Linting
        run: ruff .

  deptry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Prepare Environment
        uses: ./.github/actions/prepare

      - name: Linting
        run: deptry .

  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Prepare Environment
        uses: ./.github/actions/prepare

      - name: Type checking
        run: mypy .

  test:
    needs: [ruff, deptry, mypy]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Prepare Environment
        uses: ./.github/actions/prepare

      - name: Testing
        run: pytest .

  echo-git-diff:
    runs-on: ubuntu-latest
    steps:
      - name: Check git diff
        run: $(git diff github.base_ref github.head_ref --name-only --diff-filter=d)