name: Linters Call

on:
  workflow_call:
    inputs:
      PY_FILES:
        description: 'Changed py files in PR'
        required: true
        type: string
      REQUIREMENTS_CHANGED:
        description: 'Changed requirements files in PR'
        required: true
        type: boolean

# TODO: вынести в отдельную параметризированный action lint
jobs:
  deptry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare Environment
        uses: ./.github/actions/prepare

      - name: Linting
        run: deptry .
