name: Tests

on: workflow_call

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: KsQRooW/test-workflow

      - name: Prepare Environment
        uses: ./.github/actions/prepare

      - name: Testing
        run: pytest tests/
